version: "2"

run:
  timeout: 3m
  skip-dirs:
    - bin
    - loadtest/results

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - misspell
    - ineffassign
    - unused
    - gosec
    - goconst

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0